"""add password hash column

Revision ID: f221e484dba2
Revises: 5a0be5d14fb1
Create Date: 2026-08-30 21:46:09.449872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f221e484dba2'
down_revision = '5a0be5d14fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_places')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
        batch_op.drop_column('Picture')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Picture', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('user_places',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visited_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
